# Use custom format
format = """
[┌───────────────────>](bold green)
[│](bold green)$all
[└>](bold green) """
#format = """
#[┌───────────────────>](bold green)
#[│](bold green)$directory$rust$package
#[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10	    #Default 10 ms (in milliseconds)
command_timeout = 1000	    #Default 500 ms

# Disable the blank line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

# Disable the package module, hiding it from the prompt completely
[package]
#disabled = true
